### Create source connector
POST http://localhost:8083/connectors/ HTTP/1.1
Content-Type: application/json

{
    "name": "sqlserver-kafka-connect-connector",
    "config": {
        "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector",
        "connection.url" : "jdbc:sqlserver://host.docker.internal:5433;database=Microsoft.eShopOnContainers.Services.OrderingDb;",
        "connection.user" : "sa",
        "connection.password" : "Pass@word",
        "topic.prefix" : "cdc.order-items",
        "table-whitelist" : "ordering.orderItems",
        "mode" : "incrementing",
        "incrementing.column.name" : "Id",
        "numeric.mapping" : "best_fit"
    }
}

###Create debezium connector
POST http://localhost:8083/connectors/ HTTP/1.1
Content-Type: application/json

{
  "name": "sqlserver-debezium-connector",
  "config": {
    "connector.class": "io.debezium.connector.sqlserver.SqlServerConnector",
    "database.hostname": "host.docker.internal",
    "database.port": "5433",
    "database.user": "sa",
    "database.password": "Pass@word",
    "database.encrypt" : false,
    "database.names": "Microsoft.eShopOnContainers.Services.OrderingDb",
    "table.include.list": "ordering.orderItems",
    "topic.prefix" : "debezium",
    "decimal.handling.mode": "double",
    "schema.history.internal.kafka.bootstrap.servers": "host.docker.internal:9092", 
    "schema.history.internal.kafka.topic": "schemahistory.orders"
  }
}

### Create sink connector elastic
POST http://localhost:8083/connectors/ HTTP/1.1
Content-Type: application/json

{
    "name": "sql-server",
    "config": {
        "connector.class": "io.debezium.connector.sqlserver.SqlServerConnector",
        "database.hostname" : "host.docker.internal",
        "database.port" : "1433",
        "database.user" : "sa",
        "database.password" : "resgate@123",
        "database.names" : "Workflow",
        "database.encrypt" : false,
        "topic.prefix" : "workflows",
        "schema.history.internal.kafka.bootstrap.servers": "kafka:9092", 
        "schema.history.internal.kafka.topic": "schemahistory.workflwos",
        "database.history.kafka.bootstrap.servers" : "kafka:9092",
        "table.include.list": "wfc.Workflow" 
    }
}


### Get created connectors
GET http://localhost:8083/connectors HTTP/1.1

### List plugins
GET http://localhost:8083/connector-plugins

### Get Connector Status
GET http://localhost:8083/connectors/sql-server/status

### Get Connector Config
GET http://localhost:8083/connectors/elastic-orders-summary/config

### Get Remove connector
DELETE http://localhost:8083/connectors/sql-server
